wheel/bdist_wheel.py

When trying to help debugging a build of a package made by someone else I got confused as there was no indicated files available under the bdist directory. This PR just moves the log message to be displayed even when no `--dry-run` is defined to avoid such confusions in the future.

Log removal of bdist_dir always instead of just during a dry run

---

tests/test_metadata.py
wheel/metadata.py

Parenthesize markers before adding the `and extra == "..."` clause so it does not break the logic of the preceding expression when `or` operands are used. Fix #212.

Fix handling of requirements' environment markers.

---

tests/test_ranking.py
wheel/util.py
wheel/wininst2wheel.py

dict literals are idiomatic and Pythonic patterns that utilize modern
syntax. A dict literal is always slightly faster than a call to dict().
$ python3 -m timeit 'dict(a=1, b=2, c=3)'
10000000 loops, best of 3: 0.187 usec per loop
$ python3 -m timeit '{"a": 1, "b": 2, "c": 3}'
10000000 loops, best of 3: 0.0705 usec per loop

Prefer dict literals over calls to dict()

---

.travis.yml

using pypi resources should be minimized, and caching the packages on travis helps with that.

enable pip cache in travis build

---

tests/test_metadata.py
wheel/metadata.py

Do not strip the URLs. Fix #249.

fix handling of direct URL specifiers in requirements

---

.travis.yml
docs/story.rst

As spelled on https://pypi.org/.

Correct capitalization of PyPI

---

tests/test_metadata.py
wheel/metadata.py

Ensure extras are properly canonicalized, so corresponding `Provides-Dist` markers will match with the list of extras returned by pkg_resources. See https://github.com/pypa/pip/issues/4617.

fix handling of extras

---

docs/user_guide.rst
tests/test_bdist_wheel.py
wheel/bdist_wheel.py

This is a minor refinement to the default license/legal-related globs included in #138 , adding extension support for COPYING and NOTICE as well (since the former is often encountered with extensions, e.g. ``.txt``, ``.md``, ``.rst``; and the Apache license allows ``.txt`` as well as an extension), and also adds AUTHORS* as licenses have varying attribution requirements and they are sometimes included by reference in the licenses themselves as well. It also adds them in the docs (sorting the list alphabetically there) and adds some additional test filenames to cover these cases with varied extensions in the tests.

Add a few additional common patterns for legal and attribution files

---

wheel/bdist_wheel.py

Has been considered legacy since b2d2165fa32e2684cf1aeb0605f2ee8a2108c129 (2014-03-17) or version 0.23.0. However, projects continue to use the `[wheel]` section. Adding a warning might help move more projects to the recommended `[bdist_wheel]`.

Log a warning when the [wheel] section is used

---

docs/news.rst
wheel/wheelfile.py

`hashlib.algorithms_available` was only added in 2.7.9. Fix #258.

fix support for Python 2.7

---

docs/news.rst
wheel/metadata.py

Support for direct URL in requirements was added in 18.8 (with the switch to packaging for parsing requirements). Fix #257.

fix exceptions with older versions of setuptools

---

wheel/cli/convert.py

When converting an egg to a wheel, the period in the pyver component is correctly removed for the purposes of calculating the ABI tag and `WHEEL` tag, but the period is not removed from `egg_info['pyver']`, leading to an extraneous period being present when the wheel filename is computed with `'{name}-{ver}-{pyver}-{}-{}.whl'.format(abi, arch, **egg_info)`.
As a result, running `wheel convert` on an egg named, say, `foo-0.1.0-py3.5.egg` currently produces a wheel named `foo-0.1.0-py3.5-none-any.whl`, which is invalid (or, at the very least, inaccurate) due to the period in the pyversion tag.
This patch fixes that.

egg2wheel: Remove period from pyver in wheel filename

---

tests/cli/test_convert.py

This is a solution to https://github.com/pypa/wheel/issues/272
The pattern for regex used on `test_convert_egg` wasn’t a raw string.

Adding `r` for raw regex string on cli/test_convert.py

---

setup.py

When Python warnings are enabled, fixes warning of the form:
```
setup.py:10: ResourceWarning: unclosed file <_io.TextIOWrapper name='.../README.rst' mode='r' encoding='utf8'>
README = io.open(os.path.join(here, 'README.rst'), encoding='utf8').read()
```

Always close files in setup.py

---

docs/development.rst

In my case, while trying to setup my local environment to get a passing test suite (and without using tox), I had failures from wheel not being on the path. I had erroneously used `export PYTHONPATH=.` but that didn't work for tests that change the working directory. In desperation I actually installed a released version of wheel to the system python because I wasn't sure whether it was somehow required for bootstrapping the tests. Of course, due to version mismatches this left me in a state where some tests passed and others failed.
This PR simply advises the developer to put $PWD on the python path before running pytest.

Mention setting PYTHONPATH in dev guide

---

tests/test_metadata.py
wheel/metadata.py

There must be at least one space between the URL and the `;` delimiting the markers, as per PEP 508:
```
name_req      = name wsp* extras? wsp* versionspec? wsp* quoted_marker?
url_req       = name wsp* extras? wsp* urlspec wsp+ quoted_marker?
```
Note: there seems to be an unused `EXTRA_RE` variable in [`wheel/metadata.py`](https://github.com/pypa/wheel/blob/master/wheel/metadata.py#L15).

fix handling of direct URL requirements with markers

---

tests/test_bdist_wheel.py

Before it mistakenly duplicated 'LICENSE.txt'.

Correct default license file 'LICENCE.txt'

---

wheel/metadata.py

This fix will ensure METADATA files generated by wheel will be deterministic. 
I noticed this issue while working with `apache-airflow==1.9.0` package, the METADATA file changes between installations (in python3.6):
```
$> diff /tmp/cache/apache_airflow_1/apache_airflow-1.9.0.dist-info/METADATA /tmp/cache/apache_airflow_2/apache_airflow-1.9.0.dist-info/METADATA 
171c171
< Requires-Dist: hdfs[kerberos,dataframe,avro] (>=2.0.4) ; extra == 'devel_hadoop'
---
> Requires-Dist: hdfs[avro,kerberos,dataframe] (>=2.0.4) ; extra == 'devel_hadoop'
248c248
< Requires-Dist: hdfs[kerberos,dataframe,avro] (>=2.0.4) ; extra == 'webhdfs'
---
> Requires-Dist: hdfs[avro,kerberos,dataframe] (>=2.0.4) ; extra == 'webhdfs'
```
The fix was added the same way as this previous fix: …

Sorting requirement extras to ensure deterministic builds

---

tests/test_bdist_wheel.py
tests/test_wheelfile.py
wheel/wheelfile.py

Include directory entries when building wheel

---

docs/news.rst

Helps to reference when a feature was introduced.
All dates were obtained from PyPI.
https://pypi.org/project/wheel/#history

Document release dates

---

wheel/wheelfile.py

When creating zip entries for files and directories, only attempt to
preserve the subset of mode bits which can be reapplied through chmod,
plus the file type bits.  This will exclude any bits that are platform-
or filesystem-specific, like S_IFJOURNAL on AIX.
Fixes #291

wheelfile: Mask platform specific mode bits

---

wheel/pep425tags.py

In Python 3.8, the `m` flag is no longer appended to the SOABI, since the ABI is longer influenced by enabling pymalloc.  This PR should fix the ability to install Python 3.8 wheels on Windows.  In Python 3.8, `sys.abiflags` is an empty string.
https://docs.python.org/dev/whatsnew/3.8.html#build-and-c-api-changes
https://bugs.python.org/issue36707
See also pypa/pip#6874

Don't append "m" ABI flag in Python 3.8

---

docs/user_guide.rst

> **0.32.0 (2018-09-29)**
> ...
> * Allowed multiple license files to be specified using the `license_files` option
> * Deprecated the `license_file` option
https://wheel.readthedocs.io/en/stable/news.html

Docs: license_file was deprecated in wheel v0.32

---

wheel/metadata.py

Python 3.2 was some time ago, see PEPs 392 and 3003.

Remove legacy Python 3.2 compat statement

---

src/wheel/pep425tags.py

The resolution of issue #328 removed the custom PyPy tagging
from `get_impl_version_info()`, this just cleans up the check
that forces PyPy to call that even if `py_version_nodot` was
already set.

Issue #329: Remove last remnant of custom PyPy tags

---

src/wheel/bdist_wheel.py
tests/test_bdist_wheel.py

This is Unix's most common pattern for backup files. They are often
present, but I can't think of a good reason for them to be distributed.

Ignore files terminating in ~.

---

.github/workflows/codeqa-test.yml
src/wheel/wheelfile.py
tox.ini

In WheelFile.open(), if the hash does not exist, avoid opening the file
before raising the exception. Previously would leak the open file
resource which could result in a ResourceWarning when Python warnings
are enabled:
ResourceWarning: unclosed file <_io.FileIO name='…/test_testzip_missing_hash0/test-1.0-py2.py3-none-any.whl' mode='rb' closefd=True>
Python warnings are now enabled during tests to help catch these
earlier.

Fix resource leak in WheelFile.open()

---

docs/development.rst
docs/index.rst

Per https://groups.google.com/d/msg/pypa-dev/rUNsfIbruHM/LCEx-CB5AgAJ , pointing to distutils-sig instead.

Updated link to now-decommissioned mailing list

---

src/wheel/bdist_wheel.py
tests/test_tagopt.py

The first commit makes the fixture more specifically test for the ability to compile, and adds a test that triggers compilation failure to prove skipping works. The failing tests expose the problem in issue #374. A subsequent changeset to fix the tests is waiting for a decision whether to restore old behavior or change it.

fix regression in setting plat-name

---

docs/news.rst
src/wheel/bdist_wheel.py
tests/test_bdist_wheel.py

Fixed CRLF being used when generating WHEEL files on Windows

---

docs/news.rst
src/wheel/bdist_wheel.py
tests/test_tagopt.py

Closes #372. PyPy currently has a SOABI tag like `pypy36-pp73` (only the ABI tag) but according to PEP 3149 it should be `pypy36-pp73-x86_64-linux-gnu` (ABI tag - platform tag). PyPy may change this in an upcoming release.
This should be forward compatible, as long as the ABI tag contains a single `-`.

adapt for upcoming changes in PyPy's SOABI tag

---

.github/workflows/codeqa-test.yml
tox.ini

Python 3.10.0 final is due for release in October:
* https://www.python.org/dev/peps/pep-0619/
The first release candidate is now out and the Python release team has issued a call to action for community members:
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.10 compatibilities during this phase. As always, report any issues to the Python bug tracker.
https://discuss.python.org/t/python-3-10-0rc1-is-now-available/9982?u=hugovk
So let's also test 3.10 on the CI. The good news is everything passes.
---
I didn't yet add 3.10 to the `classifiers` etc., that can wait until 3.10 is released and officially supported, but could be updated now if you wish.
I also added quotes around version numbers in YAML so it doesn't later interpret `3.10` as …

Test Python 3.10 release candidate

---

.github/workflows/codeqa-test.yml

See https://github.com/actions/setup-python. PyPy 3.6 is no longer supported, so using 3.7.

ci: fix pypy & use Python 3.10.0

---

.pre-commit-config.yaml
docs/story.rst
tox.ini

I've added a few more checks; the main one that triggered a bit was the RST check, which found some markdown syntax in an RST file.
I've also moved tox over to running pre-commit, for consistency. There's now a `tox -e lint` job, and the old separate jobs were removed. Though you can run individual checks, so if you care about them, I can add them back in.

style: a few more checks, and Tox access to pre-commit

---

docs/development.rst
tests/test_bdist_wheel.py

Remove redundant Python < 3.6 skips

---

docs/quickstart.rst
docs/user_guide.rst

Fixes https://github.com/pypa/wheel/issues/424.
Use https://github.com/pypa/build instead of invoking `setup.py` directly.
See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for the long version.
And https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html#summary for the summary.

Recommend build instead of invoking setup.py directly

---

.github/workflows/test.yml

Reconfigures the build matrix to include Python 3.11 (which is currently in beta) and PyPy 3.9. PyPy 3.8 is also added and 3.7 is removed.
All Python versions (3.7 to 3.11, and PyPy 3.8 and 3.9) are tested on Ubuntu, and the latest stable versions (currently Python 3.10 and PyPy 3.9) also on macOS and Windows.
A weekly scheduled run is also added to catch changes in dependencies and environments (each Monday at 06:00 UTC), and `workflow_dispatch` is added to be able to manually trigger the CI workflow.
The used actions are updated to v3 and caching is now configured in the setup-python action.

CI: Reconfigure build matrix for Python 3.11 and PyPy 3.9

---

docs/news.rst
setup.cfg
src/wheel/bdist_wheel.py
tests/test_bdist_wheel.py

As discussed in #465, `bdist_wheel` will behave differently when `license_files` is specified in `setup.py` or in `setup.cfg`.
The main idea of this PR is to make the behaviour consistent across these different possibilities.
I am supposing that the original intention of the `wheel` authors was to also support distributions using `from distutils.core import setup` in addition to `from setuptools import setup`.
In my mind this justifies the choice for `distribution.get_option_dict("metadata")` instead of simply looking up in `distribution.metadata`.
Therefore, I am attempting to preserve this backward compatibility in the PR.
If this is not required the implementation. can be further simplified.
Closes #444.
Closes #465.

Add support for `license_files` specified in `setup.py`

---

docs/news.rst
src/wheel/bdist_wheel.py
tests/test_bdist_wheel.py

In #373 I started fixing the SOABI parsing to trim off the platform tag from the ABI tag. I used the wrong logic: the `soabi.startswith("pypy-")`  would not be True. This means the code on line 96 was used for PyPy. No harm was done, but if PyPy updates its SOABI tag to fix [this issue](https://foss.heptapod.net/pypy/pypy/-/issues/3816), the fix here will be needed.
Edit: to be clear: the SOABI is currently `pypy36-pp73`, which does not start with `pypy-`

fix PyPy SOABI parsing

---

docs/news.rst
setup.cfg
src/wheel/bdist_wheel.py
src/wheel/cli/convert.py
tests/test_bdist_wheel.py

Removed install dependency on setuptools

---

src/wheel/bdist_wheel.py
tests/test_bdist_wheel.py

`setuptools` produces UTF-8 `PKG-INFO` files. However, after processed by `wheel`, some serialization problems show up in the `METADATA` file (see https://github.com/pypa/setuptools/issues/3663#issuecomment-1308717064)
This PR attempts to allow UTF-8 in `METADATA`[^1] produced by wheel.
Closes #488.
[^1]: Initially, I was not 100% sure if the issue was related to standardization. PyPA specs do mention a bunch of old RFCs, but they are also clear state that ["strings must be serialised using the UTF-8 encoding"](https://packaging.python.org/en/latest/specifications/core-metadata/). Flit adopts the UTF-8 approach.

Allow `METADATA` file to contain UTF-8 chars

---

docs/reference/wheel_unpack.rst

The long Argument for unpack is `--dest` and not `--dest-dir`

Fix typo in documentation

---

src/wheel/bdist_wheel.py
tests/test_bdist_wheel.py

Without this, wheels produced on such platforms will cause a `WheelError`.
For example: https://gist.github.com/tucked/871d4ec2364379249bf524cf3a42f308

Replace spaces in platform names with underscores

---

tests/cli/test_convert.py
tests/cli/test_pack.py
tests/cli/test_unpack.py
tests/conftest.py
tests/test_bdist_wheel.py
tests/test_metadata.py
tests/test_tagopt.py
tests/test_wheelfile.py

This uses pathlib-based tmp_path instead of py.path based tmpdir fixtures. Should be fine for pytest 6+, I think. Came up in the context of #512, though you can't quite remove the `_pytest` warning suppression, as there's one remaining thing in pytest that is missing an encoding.

tests: use modern tmp_path instead of py.path based tmpdir

---

.github/workflows/test.yml
pyproject.toml
src/wheel/bdist_wheel.py
src/wheel/metadata.py
tests/cli/test_convert.py

For reference, this is PEP 597, in Python 3.10+, and happens when PYTHONWARNDEFAULTENCODING is set.
This cherry-picks @methane's #504, but adds two new commits; one that adds testing for this (using my favorite pytest settings), and one that fixes two more cases of missing encodings discovered by adding those tests.

fix: EncodingWarning

---

docs/news.rst
src/wheel/cli/unpack.py
tests/cli/test_unpack.py

Fixed `wheel unpack` not setting the executable bit

---

docs/news.rst

Missed from #422 and #501. Closes #407.

docs: add a couple of missing changelog entries

---

pyproject.toml

This line doesn't do anything, as flit-core ignores it - the METADATA doesn't have a place for a full-text license. The license is specified via trove classifiers, and Flit automatically includes LICENSE* in the dist-info directory, `wheel-0.40.0.dist-info/LICENSE.txt` is still present after this change. See #518.

chore: remove unused license line

---

docs/news.rst
src/wheel/cli/__init__.py
src/wheel/cli/tags.py
tests/cli/test_tags.py

Allowed string components after initial number of build tags in `wheel tags`

---

.github/workflows/test.yml
pyproject.toml

Add Python 3.12 to the Ubuntu job matrix to start testing the betas in the CI.

CI: Start testing Python 3.12

---

pyproject.toml

See https://github.com/scientific-python/cookie/issues/201.

chore: both ruff and black read requires-python now

---

.github/codecov.yml

This should make patch coverage only informational.

ci: make patch coverage informational only

---

docs/news.rst
src/wheel/bdist_wheel.py
tests/test_bdist_wheel.py

Removing warning on 3.12 alphas. Closes #526.
This drops support for the early 3.12 alphas, but older alphas aren't usually actively supported anyway. LMK if they need support too.

fix: remove warning on 3.12a7+

---

pyproject.toml
src/wheel/bdist_wheel.py
src/wheel/wheelfile.py

Some small changes that might be helpful. Comments will be inline.

chore: some touchups & 3.12 classifier

---

docs/news.rst
src/wheel/metadata.py
tests/test_metadata.py

Don't wrap version specifiers in parens in Requires-Dist

---

docs/news.rst
src/wheel/bdist_wheel.py
tests/test_bdist_wheel.py
tests/test_macosx_libfile.py

- use `struct.calcsize("P") == 4` rather than `sys.maxsize == 2147483647` to check for 32bit interpreter
(same as stdlib `platform.architecture` [default implementation](https://github.com/python/cpython/blob/4d4393139fae39db26dead33529b6ae0bafbfc58/Lib/platform.py#L713-L716))
- extend the 32bit check to `linux-aarch64` => `linux-armv7l` (fixes #367)
The first one fixes platform tag detection with GraalPy (xref https://github.com/pypa/packaging/issues/710 / https://github.com/pypa/packaging/issues/711)

fix: platform tag detection

---

src/wheel/bdist_wheel.py
src/wheel/wheelfile.py

Since Python 3.7 the insertion order to `dict` has been preserved, thus OrderedDict is no longer necessary.

Remove use of OrderedDict, simplify a str concat

---

docs/news.rst
src/wheel/cli/tags.py
tests/cli/test_tags.py

Closes #558
<s>Tests are not included yet, but advice would be welcome. The example with tests/test_tagopt.py would probably needed to be modified to add some dummy [data files](https://setuptools.pypa.io/en/latest/userguide/datafiles.html) in a subdir.</s> Some testing has been modified, but advice on more is welcome.
<s>This PR also removes (now) unnecessary use of OrderedDict, and tidies a str concat.</s>

Skip adding directories to RECORD with `wheel tags`

---

docs/news.rst
src/wheel/bdist_wheel.py
tests/test_bdist_wheel.py

https://github.com/pypa/packaging/pull/607 changed the ABI tag computation for [GraalPy](https://github.com/oracle/graalpython). This results in the current wheel not working for GraalPy because it uses pypa/packaging to validate tags of newly built wheels and now it always rejects them as mismatched. We need a corresponding change in wheel's tag computation, like it was done for PyPy in https://github.com/pypa/wheel/pull/373. Our SOABI look something like `graalpy231-310-native-x86_64-linux`, so the expected ABI tag for that is `graalpy231_310_native`. Compared to PyPy's there is one more component to distinguish native and sandboxed modes.
CC @timfel

Produce correct ABI tags for GraalPy

---

docs/news.rst
src/wheel/bdist_wheel.py
tests/test_bdist_wheel.py

CPython 3.13a1 on Windows now provides the SOABI sysconfig variable. However, the SOABI (and extension suffixes) are different on Windows than on Linux and macOS, e.g. `cp310-win_amd64` vs. `cpython-313-darwin`.
Fixes #576

Fix ABI tag for CPython 3.13 on Windows

---

docs/news.rst
src/wheel/bdist_wheel.py
src/wheel/cli/__init__.py
src/wheel/cli/convert.py
src/wheel/cli/pack.py
src/wheel/cli/tags.py
tests/cli/test_pack.py
tests/cli/test_tags.py

The PyPA Binary Distribution Format spec [says](https://packaging.python.org/en/latest/specifications/binary-distribution-format/#file-contents) the `WHEEL` metadata file is "in the same basic key: value format" as the `METADATA` file.  `METADATA` in turn is governed by the Core Metadata Specifications, which [say](https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata-specifications):
> In the absence of a precise definition, the practical standard is set by what the standard library email.parser module can parse using the compat32 policy.
`wheel.bdist_wheel` accordingly uses `email.generator.BytesGenerator` to generate `WHEEL`, but the CLI `pack` and `tags` commands opt to hand-implement `WHEEL` parsing and mutation.  Their mutation functions, `set_tags()` …

Several fixes to `WHEEL` metadata handling

---

pyproject.toml

Apply a [Repo-Review](https://learn.scientific-python.org/development/guides/repo-review/?repo=pypa%2Fwheel&branch=main) suggestion.
* RF202: Use (new) lint config section
`select` should be set as `lint.select` instead

Apply Repo-Review suggestion

---

.pre-commit-config.yaml

I was reading through the history of `wheel` and a lot of it is autoupdate. Opening this PR in case it's welcome, feel free to close!

Reduce frequency of pre-commit autoupdate

---

docs/index.rst

And the dev list has been archived.
Perhaps replace with https://discuss.python.org?

The virtualenv Google group does not exist any more

---

src/wheel/macosx_libfile.py

Function `get_base_class_and_magic_number()` already tests the value of `seek`, followed by a `seek()` call if needed. No need to duplicate the code in calling function `read_mach_header()`.
Fixes https://github.com/pypa/wheel/pull/591#issuecomment-1860528615.

Remove duplicate seek test

---

src/wheel/vendored/packaging/markers.py
src/wheel/vendored/packaging/tags.py

UP032 Use f-string instead of `format` call
Not sure why CI jobs don't catch this, especially after updating ruff from 0.3.5 to 0.4.3 in 0b7771e.

Apply new ruff/pyupgrade rule UP032

---

pyproject.toml

It's useful to run ruff locally sometimes, like to add `--unsafe-fixes`. This ensures it doesn't format or change something it shouldn't. See https://github.com/pypa/wheel/pull/617.

chore: make sure local ruff runs don't touch vendored

---

tests/conftest.py

Skip the tests using abi3 extension when the freethreading build is used, as Python 3.13 freethreading does not support the limited API and its use results in a build error.
Fixes #636

Skip abi3 tests when freethreading Python build is used

---

docs/news.rst
src/wheel/bdist_wheel.py

While working on [the implementation of PEP 643](https://github.com/pypa/setuptools/pull/4698), I realised that if we implement a new version of metadata in `setuptools`, once the current version of `wheel.bdist_wheel` runs in deprecated scenarios, it will produce invalid metadata.
We can also expand this reasoning to other fixes and/or PEP implementations. A recent example was the fix for https://github.com/pypa/setuptools/issues/1825, proposed in https://github.com/pypa/setuptools/pull/4647, which caused some trouble and required the implementation of a very intrusive workaround: https://github.com/pypa/setuptools/pull/4684#issuecomment-2431247361.
I was thinking if there was any way we could address that while maintaining as much as possible a backwards compatible API (in both …

Improve compatibility with future versions of `setuptools`

---

.pre-commit-config.yaml
docs/news.rst
pyproject.toml
src/wheel/cli/convert.py
tests/cli/test_convert.py

This also aims to improve the correctness of the egg and bdist_wininst conversions.
Fixes #510.

Refactored the `wheel convert` command to not require setuptools

---

docs/news.rst
src/wheel/cli/convert.py
tests/cli/test_convert.py

To prevent an exception, check for an empty description Fixes: #645
Test plan: Run the unit tests without the fix -> Fails with an exception. Passes after the fix

Check for empty description when converting metadata

---

docs/news.rst

Link to the issue about breakage on MacOS in 0.46.0 release is broken, which seems a typo. It's confusing to be brought to a 404 page when reading through the release note.
Fixes: 98617630542d ("Restored the wheel.macosx_libfile module for setuptools")

Fix issue link in 0.46.1 release note
